### ISSUE TITLE
Fetch only Law Schools

### ISSUE THREAD

**Issue by ali-ehmed** [karllhughes/colleges#1]
Hey @karllhughes the api has fantastic structure although I just need to know whether it's been implemented yet or you can do some slight change that If I only want to filter Law schools or Schools that provide legal education within the collection. Is it possible?

**Comment by karllhughes** [comment]
@aliahmed922 there is no easy way to filter by whether a school provides legal education or not. The raw data is in [a CSV file here](https://raw.githubusercontent.com/karllhughes/colleges/master/seeds/files/colleges_2016_03.csv), and as you'll see, we don't track the individual programs each college offers.

Not sure what your use case is, but you might be able to grab the data from Wikipedia here: https://en.wikipedia.org/wiki/List_of_law_schools_in_the_United_States
