### ISSUE TITLE
University Logo search

### ISSUE THREAD

**Issue by ghost** [karllhughes/colleges#2]
Does this still work. I tried to use a couple of the URLs and your main page as examples and none of them work I was wondering if this still is a useful?

https://colleges.khughes.me/api/colleges/8d4052a5-e171-4717-9222-34fb4fc5836f

**Comment by karllhughes** [comment]
Hey @harrygj if you follow the [local setup instructions](https://github.com/karllhughes/colleges#local-setup), you can run your own instance of this API, but I no longer maintain a public API for free.

It also doesn't include logos, so it might not be helpful if that's what you're wanting.

You might be able to get college logos by searching for them on [Clearbit](https://clearbit.com/logo).
